apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nebula-control-plane
  namespace: default
  labels:
    app: nebula-control-plane
    version: v1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      labels:
        app: nebula-control-plane
        version: v1
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: nebula-service-account@intelligentmachines.iam.gserviceaccount.com
      containers:
      - name: nebula-control-plane
        image: gcr.io/intelligentmachines/nebula-control-plane:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nebula-secrets
              key: database-url
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: nebula-secrets
              key: database-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nebula-secrets
              key: database-password
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: nebula-secrets
              key: gemini-api-key
        - name: GEMINI_PROJECT_ID
          value: "intelligentmachines"
        - name: GCP_PROJECT_ID
          value: "intelligentmachines"
        - name: GCP_REGION
          value: "us-central1"
        - name: TEAMS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: nebula-secrets
              key: teams-client-id
        - name: TEAMS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: nebula-secrets
              key: teams-client-secret
        - name: TEAMS_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: nebula-secrets
              key: teams-tenant-id
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nebula-secrets
              key: jwt-secret
        - name: ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: nebula-secrets
              key: admin-api-key
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /nebula-control-plane/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /nebula-control-plane/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /nebula-control-plane/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
  traffic:
  - percent: 100
    latestRevision: true